{% set version = "1.42.0" %}
{% set name = "grpcio-tools" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0a0daa82eb2c2fb8e12b82a458d1b7c5516fe1135551da92b1a02e2cba93422
  patches:
    - 0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - grpcio =={{ version }}
    - pip
    - protobuf >=3.6.0
    - python
  run:
    - grpcio =={{ version }}
    - protobuf >=3.6.0
    - python

test:
  imports:
    - grpc_tools

about:
  home: https://grpc.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Protobuf code generator for gRPC
  doc_source_url: https://github.com/grpc/grpc/tree/master/doc
  doc_url: https://grpc.io/docs/
  dev_url: https://github.com/grpc/grpc/tree/master/tools

extra:
  recipe-maintainers:
    - martinRenou
